spring:
  application:
    name: curriculum-api
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    druid:
      min-evictable-idle-time-millis: 300000
      time-between-eviction-runs-millis: 60000
      test-while-idle: true
      validation-query: SELECT 1
  redis:
    host: ${redis.host}
    port: ${redis.port}
    password: ${redis.password}
    database: ${redis.database}

  profiles:
    active: local
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
# mail 配置保持注释

springfox:
  documentation:
    enabled: true

server:
  port: 10101

minio:
  endpoint: ${minio.endpoint}
  accessKey: ${minio.accessKey}
  secretKey: ${minio.secretKey}
  bucket:
    bucket_mediaFiles: ${minio.bucket.bucket_mediaFiles}
    bucket_video: ${minio.bucket.bucket_video}
    bucket_image: ${minio.bucket.bucket_image}

curriculum:
  jwt:
    user-secret-key: ${curriculum.jwt.user-secret-key}
    user-ttl: ${curriculum.jwt.user-ttl}
    user-token-name: ${curriculum.jwt.user-token-name}
  aliyun:
    sms:
      accessKeyId: ${curriculum.aliyun.sms.accessKeyId}
      accessKeySecret: ${curriculum.aliyun.sms.accessKeySecret}
      endpoint: ${curriculum.aliyun.sms.endpoint}
      signName: ${curriculum.aliyun.sms.signName}
      smsCodeTemplateCode: ${curriculum.aliyun.sms.smsCodeTemplateCode}

alipay:
  pay:
    APP_ID: ${alipay.pay.APP_ID}
    APP_PRIVATE_KEY: ${alipay.pay.APP_PRIVATE_KEY}
    ALIPAY_PUBLIC_KEY: ${alipay.pay.ALIPAY_PUBLIC_KEY}
    notifyurl: ${alipay.pay.notifyurl}
    returnurl: ${alipay.pay.returnurl}
    url: ${alipay.pay.url}
    charset: UTF-8
    format: json
    log-path: /log
    sign-type: RSA2
