spring:
  application:
    name: curriculum-api
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/test?serverTimezone=UTC&userUnicode=true&useSSL=false&
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    druid:
      min-evictable-idle-time-millis: 300000
      time-between-eviction-runs-millis: 60000
      test-while-idle: true
      validation-query: SELECT 1
  redis:
    host: localhost
    port: 6379
    password: ${redis.password}
    database: 10

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
# mail 配置保持注释

springfox:
  documentation:
    enabled: true

server:
  port: 10101

minio:
  endpoint: ${minio.endpoint}
  accessKey: ${minio.accessKey}
  secretKey: ${minio.secretKey}
  bucket:
    bucket_mediaFiles: ${minio.bucket.bucket_mediaFiles}
    bucket_video: ${minio.bucket.bucket_video}
    bucket_image: ${minio.bucket.bucket_image}

curriculum:
  jwt:
    user-secret-key: ${curriculum.jwt.user-secret-key}
    user-ttl: ${curriculum.jwt.user-
